# Generated by Django 4.1.7 on 2023-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_wishlistitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='supermarkets',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='supermarkets',
            field=models.ManyToManyField(to='offers.supermarket'),
        ),
    ]
